# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

# Set command timeout to 3 second
command_timeout = 3000

[kubernetes]
disabled = false

[conda]
format = "[$symbol$environment](dimmed green) "

[aws]
disabled = true

[directory]
truncation_length = 1
fish_style_pwd_dir_length = 1

[time]
disabled = false
format = '🕙 [\[ $time \]]($style) '
time_format = '%T'
utc_time_offset = 'local'

[line_break]
disabled = true
