#!/usr/bin/env sh
#YABAI STUFF

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label one
yabai -m space 2 --label two

# float system preferences. Most of these just disable Yabai from resizing them.
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Karabiner-Elements$" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
yabai -m rule --add app="^Disk Utility$" manage=off
yabai -m rule --add app="^System Information$" manage=off
yabai -m rule --add app="^Activity Monitor$" manage=off
yabai -m rule --add app="^FaceTime$" manage=off
yabai -m rule --add app="^ImageOptim$" manage=off
yabai -m rule --add app="^VNC Viewer$" manage=off
yabai -m rule --add app="^ChatGPT$" manage=off
yabai -m rule --apply

## Some random global settings
# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0

## Change how yabai looks
yabai -m config --space 1 layout stack
yabai -m config --space 2 layout float
yabai -m config top_padding 10
yabai -m config bottom_padding 10
yabai -m config left_padding 10
yabai -m config right_padding 10
yabai -m config window_gap 10

echo "yabai configuration loaded.."

#END
